"""Shared shape table for blockwise FP8 GEMM scoring on MI300X / gfx942.

Two reference columns per (shape, section):

  listed_tflops   user-supplied competitor table (Primus-Turbo through-
                  autograd path: gemm_fp8_impl via @torch.library.custom_op
                  for fwd/dgrad, gemm_fp8_blockwise_wgrad_kc_triton_kernel
                  for wgrad). Shown for context.

  triton_tflops   THIS-machine raw-call live measurement of the same Triton
                  kernels (no autograd, no custom_op dispatch). For wgrad
                  uses the K-contig path; for fwd/dgrad raw calls the same
                  triton kernel Primus-Turbo uses. Updated by
                  scripts/_bench_blockwise_triton_target_shapes.py.

Target = triton_tflops × TARGET_MULTIPLIER (HK must beat THIS-machine
Triton by 25% to score 1.0). This makes the bar reproducible — re-run the
Triton bench and regenerate TRITON_BASELINE if the machine state changes.

Pure (non-grouped, single-kernel-per-call) DeepSeek-V3-style 1×128 / 128×128
block-scaled FP8 GEMM. Total FLOPs per call = 2 × M × N × K.

Sections map to GEMM layouts (standard MLP fwd/bwd):
  fwd   → RCR (NT) : C[M,N] = A[M,K] @ B[N,K]^T   (Y = X @ W^T)
  dgrad → RRR (NN) : C[M,K] = A[M,N] @ B[N,K]      (dX = dY @ W)
  wgrad → CRR (TN) : C[N,K] = A[M,N]^T @ B[M,K]    (dW = dY^T @ X, K-contig)
"""

from __future__ import annotations

from dataclasses import dataclass

TARGET_MULTIPLIER = 1.25


@dataclass(frozen=True)
class ShapeRow:
    model: str
    op: str           # GateUP | Down
    M: int
    N: int
    K: int
    fwd_tflops:   float
    dgrad_tflops: float
    wgrad_tflops: float

    @property
    def name(self) -> str:
        return f"{self.model}.{self.op}.M{self.M}.N{self.N}.K{self.K}"

    def listed(self, section: str) -> float:
        return {"fwd": self.fwd_tflops,
                "dgrad": self.dgrad_tflops,
                "wgrad": self.wgrad_tflops}[section]

    def triton(self, section: str) -> float:
        """THIS-machine Triton raw-call baseline (from TRITON_BASELINE below).
        Falls back to listed if no entry."""
        entry = TRITON_BASELINE.get(self.name)
        if entry is None:
            return self.listed(section)
        return entry.get(section, self.listed(section))

    def target(self, section: str) -> float:
        """HK target = TARGET_MULTIPLIER × this-machine Triton."""
        return self.triton(section) * TARGET_MULTIPLIER


# 18 production-model GEMM shapes, M ∈ {8192, 16384, 32768}.
# Listed numbers from user's target table (per-kernel blockwise FP8 timing).
SHAPES: list[ShapeRow] = [
    # (model, op, M, N, K, fwd, dgrad, wgrad)
    ShapeRow("LFM2-8B-A1B",     "GateUP",  8192, 3584, 2048, 355, 345, 379),
    ShapeRow("LFM2-8B-A1B",     "GateUP", 16384, 3584, 2048, 478, 417, 438),
    ShapeRow("LFM2-8B-A1B",     "GateUP", 32768, 3584, 2048, 594, 533, 486),
    ShapeRow("LFM2-8B-A1B",     "Down",    8192, 2048, 1792, 238, 228, 315),
    ShapeRow("LFM2-8B-A1B",     "Down",   16384, 2048, 1792, 361, 311, 384),
    ShapeRow("LFM2-8B-A1B",     "Down",   32768, 2048, 1792, 478, 415, 446),

    ShapeRow("Qwen3-235B-A22B", "GateUP",  8192, 3072, 4096, 436, 403, 449),
    ShapeRow("Qwen3-235B-A22B", "GateUP", 16384, 3072, 4096, 574, 523, 512),
    ShapeRow("Qwen3-235B-A22B", "GateUP", 32768, 3072, 4096, 678, 580, 530),
    ShapeRow("Qwen3-235B-A22B", "Down",    8192, 4096, 1536, 330, 299, 359),
    ShapeRow("Qwen3-235B-A22B", "Down",   16384, 4096, 1536, 436, 357, 404),
    ShapeRow("Qwen3-235B-A22B", "Down",   32768, 4096, 1536, 566, 464, 454),

    ShapeRow("DeepSeek-V3",     "GateUP",  8192, 4096, 7168, 637, 489, 569),
    ShapeRow("DeepSeek-V3",     "GateUP", 16384, 4096, 7168, 744, 582, 619),
    ShapeRow("DeepSeek-V3",     "GateUP", 32768, 4096, 7168, 790, 579, 608),
    ShapeRow("DeepSeek-V3",     "Down",    8192, 7168, 2048, 475, 438, 478),
    ShapeRow("DeepSeek-V3",     "Down",   16384, 7168, 2048, 597, 489, 551),
    ShapeRow("DeepSeek-V3",     "Down",   32768, 7168, 2048, 728, 581, 590),
]

SECTIONS = ("fwd", "dgrad", "wgrad")
LAYOUT_BY_SECTION = {"fwd": "RCR/NT", "dgrad": "RRR/NN", "wgrad": "CRR/TN"}

# ────────────────────────────────────────────────────────────────────────────
# Triton baseline (this MI300X, ROCm 7.2.0)
# Generated by scripts/_bench_blockwise_triton_target_shapes.py — wgrad uses
# K-contig path (gemm_fp8_blockwise_wgrad_kc_triton_kernel) to match the
# methodology of the listed numbers. fwd/dgrad are raw-call Triton (slightly
# higher than through-autograd 'listed' on small shapes, closer to rocprof
# kernel-only ground truth).
# Re-generate after machine changes:
#   rm scripts/.bench_blockwise_triton_target_shapes_cache.json
#   python3 scripts/_bench_blockwise_triton_target_shapes.py
#   python3 scripts/_bench_blockwise_triton_target_shapes.py --update-baseline
# ────────────────────────────────────────────────────────────────────────────
TRITON_BASELINE: dict[str, dict[str, float]] = {
    "LFM2-8B-A1B.GateUP.M8192.N3584.K2048":     {"fwd": 484.8, "dgrad": 393.9, "wgrad": 408.1},
    "LFM2-8B-A1B.GateUP.M16384.N3584.K2048":    {"fwd": 626.2, "dgrad": 481.1, "wgrad": 469.1},
    "LFM2-8B-A1B.GateUP.M32768.N3584.K2048":    {"fwd": 718.9, "dgrad": 584.2, "wgrad": 518.8},
    "LFM2-8B-A1B.Down.M8192.N2048.K1792":       {"fwd": 351.2, "dgrad": 331.0, "wgrad": 341.8},
    "LFM2-8B-A1B.Down.M16384.N2048.K1792":      {"fwd": 490.4, "dgrad": 407.1, "wgrad": 448.0},
    "LFM2-8B-A1B.Down.M32768.N2048.K1792":      {"fwd": 627.6, "dgrad": 540.2, "wgrad": 501.7},
    "Qwen3-235B-A22B.GateUP.M8192.N3072.K4096": {"fwd": 566.3, "dgrad": 425.4, "wgrad": 498.1},
    "Qwen3-235B-A22B.GateUP.M16384.N3072.K4096":{"fwd": 704.1, "dgrad": 532.4, "wgrad": 562.3},
    "Qwen3-235B-A22B.GateUP.M32768.N3072.K4096":{"fwd": 756.3, "dgrad": 596.9, "wgrad": 588.3},
    "Qwen3-235B-A22B.Down.M8192.N4096.K1536":   {"fwd": 454.5, "dgrad": 377.9, "wgrad": 373.6},
    "Qwen3-235B-A22B.Down.M16384.N4096.K1536":  {"fwd": 575.3, "dgrad": 505.2, "wgrad": 402.9},
    "Qwen3-235B-A22B.Down.M32768.N4096.K1536":  {"fwd": 685.0, "dgrad": 550.4, "wgrad": 433.3},
    "DeepSeek-V3.GateUP.M8192.N4096.K7168":     {"fwd": 767.3, "dgrad": 570.6, "wgrad": 606.8},
    "DeepSeek-V3.GateUP.M16384.N4096.K7168":    {"fwd": 787.7, "dgrad": 646.9, "wgrad": 641.4},
    "DeepSeek-V3.GateUP.M32768.N4096.K7168":    {"fwd": 785.6, "dgrad": 644.4, "wgrad": 643.9},
    "DeepSeek-V3.Down.M8192.N7168.K2048":       {"fwd": 624.1, "dgrad": 484.6, "wgrad": 560.5},
    "DeepSeek-V3.Down.M16384.N7168.K2048":      {"fwd": 716.8, "dgrad": 563.2, "wgrad": 615.2},
    "DeepSeek-V3.Down.M32768.N7168.K2048":      {"fwd": 740.7, "dgrad": 581.9, "wgrad": 596.6},
}

# ────────────────────────────────────────────────────────────────────────────
# HK blockwise FP8 kernel capability gates (kernels/gemm/fp8fp32/mi300x/
# blockwise_8192/blockwise.cpp)
# ────────────────────────────────────────────────────────────────────────────
# Current state (= what the kernel literally implements right now):
#   - runtime M/N/K (round-1 made M = A.rows(), N = B.rows() runtime; K = A.cols())
#   - BLOCK_M = 256 (M%256==0), BLOCK_N = 128 (N%128==0), BLOCK_K = 128 (K%128==0)
#   - fwd RCR (NT) and dgrad RRR (NN; routed through fwd kernel via Python-
#     side B-transpose, round-8). Per-section block rules:
#       fwd:   M%256, N%128, K%128
#       dgrad: M%256, N%128, K%128 (B is pre-transposed Python-side)
#   - wgrad CRR (TN) capability EXISTS in blockwise.cpp + test_python.py
#     (round-46: K-contig col-T input convention, dispatch_micro_wgrad routes
#     through dispatch_micro). Verified at 8192³: SNR 49.58 dB / 750 TFLOPS.
#     Gate is intentionally still SKIPped here in round-47 because enabling
#     all 18 wgrad shapes triples the metric invocation count to 54×5×~2s ≈
#     540s, exceeding the daemon's 480s metric_timeout (round-2 of run
#     20260512_005153 hit `[metric] TIMEOUT after 480s`). Re-enable when
#     either: (a) test_python.py amortizes import overhead across shapes,
#     (b) daemon runs with larger --metric-timeout, or (c) wgrad is enabled
#     for a small subset of shapes only.
#
# Every shape × section that doesn't pass the gate scores 0 in the metric.
# As the kernel evolves, the per-shape gate becomes None for that section and
# the score naturally rises.

HK_FP8_BLOCK_M = 256
HK_FP8_BLOCK_N = 128
HK_FP8_BLOCK_K = 128


def hk_fp8_unsupported_reason(row: ShapeRow, section: str) -> str | None:
    """Return None if HK FP8 kernel can measure this (shape, section), else
    a short string explaining what blocks it. Used by the metric to report
    SKIP reasons so the gap is visible per row."""
    if section == "wgrad":
        # Capability EXISTS for all 18 shapes (round-46 dispatch_micro_wgrad
        # → dispatch_micro via K-contig col-T inputs). Round-48/49 only
        # enabled M∈{8192,16384} to fit the daemon's 480s metric_timeout.
        # Gate lifted manually 2026-05-12 (post-handover): the SKIP'd 6
        # M=32768 shapes have 4× larger input gen but kernel runtime is
        # bandwidth-bound, not 4× per call — should fit easily without daemon
        # in the loop. If re-launching daemon, bump --metric-timeout to 720+.
        # wgrad routes through fwd kernel with relabeling M_fwd=N, N_fwd=K,
        # K_fwd=M, so check the relabeled dims against fwd's block constraints.
        if row.N % HK_FP8_BLOCK_M:
            return f"wgrad: N={row.N} not divisible by BLOCK_M={HK_FP8_BLOCK_M} (M_fwd)"
        if row.K % HK_FP8_BLOCK_N:
            return f"wgrad: K={row.K} not divisible by BLOCK_N={HK_FP8_BLOCK_N} (N_fwd)"
        if row.M % HK_FP8_BLOCK_K:
            return f"wgrad: M={row.M} not divisible by BLOCK_K={HK_FP8_BLOCK_K} (K_fwd)"
        return None
    # fwd → RCR, dgrad → RRR (both supported since round-8; same block rules).
    if row.M % HK_FP8_BLOCK_M:
        return f"M={row.M} not divisible by BLOCK_M={HK_FP8_BLOCK_M}"
    if row.N % HK_FP8_BLOCK_N:
        return f"N={row.N} not divisible by BLOCK_N={HK_FP8_BLOCK_N}"
    if row.K % HK_FP8_BLOCK_K:
        return f"K={row.K} not divisible by BLOCK_K={HK_FP8_BLOCK_K}"
    return None
